const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=process.env.PORT||3000, ROOT=path.join(__dirname,'public');
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.svg':'image/svg+xml','.json':'application/json'};
const rooms=new Map();
const stages=[
 {title:'The Threshold',type:'sequence',story:'The vault wakes only when two witnesses remember the same pattern.',a:{label:'YOUR RELIC',items:['△','○','◇','□'],hint:'The symbols are arranged from three edges to four.'},b:{label:'PARTNER RELIC',items:['□','◇','○','△'],hint:'Read your partner\'s relic from the bottom upward.'},answer:'△○◇□'},
 {title:'Split Signal',type:'signal',story:'A pulse crosses the chamber. One player sees the waveform; the other sees its language.',a:{label:'PULSE',items:['SHORT','LONG','LONG','SHORT','SHORT']},b:{label:'KEY',items:['S = SHORT','L = LONG'],hint:'Translate the pulse exactly.'},answer:'SLLSS'},
 {title:'Four Locks',type:'code',story:'Four locks, four clues. Neither side owns the full number.',a:{label:'LEFT CLUES',items:['1st digit = 7','3rd digit is 2 higher than 1st','Sum of 1st + 4th = 11']},b:{label:'RIGHT CLUES',items:['2nd digit = 4','4th digit = 4','The 2nd and 4th locks share the same value'],hint:'Use all clues together.'},answer:'7494'},
 {title:'Mirror Room',type:'mirror',story:'The safe opens when both mirrors point the beam toward the core.',a:{label:'YOUR GRID',items:['↘','→','↗','↓','↙'],hint:'Choose the orientation that continues the beam.'},b:{label:'PARTNER GRID',items:['↑','↖','←','↙','↘']},answer:'3-4'},
 {title:'Dead Drop',type:'word',story:'A phrase was cut in half. Your partner holds the missing half.',a:{label:'FRAGMENT A',items:['THE','KEY','SLEEPS','UNDER'],hint:'Complete the sentence.'},b:{label:'FRAGMENT B',items:['THE','THIRD','STAR'],hint:'Arrange the fragments naturally.'},answer:'THEKEYSLEEPSUNDERTHE THIRDSTAR'.replace(/ /g,'')},
 {title:'Pressure',type:'sync',story:'The floor is a shared instrument. Both players must choose the same rhythm.',a:{label:'RHYTHM A',items:['●','●','○','●','○','○']},b:{label:'RHYTHM B',items:['●','●','○','●','○','○']},answer:'110100'},
 {title:'The Archivist',type:'logic',story:'Three names, three doors. One statement is true.',a:{label:'ARCHIVE A',items:['ARI says: Door II is safe.','NOA says: Door I is not safe.']},b:{label:'ARCHIVE B',items:['SAM says: Door II is not safe.','Exactly one statement is true.'],hint:'Only one of the three statements can be true.'},answer:'I'},
 {title:'Glass Cipher',type:'cipher',story:'The glass displays a Caesar-shifted word. Your partner knows the shift.',a:{label:'CIPHER',items:['KHOOR'],hint:'A classic Caesar shift hides the word.'},b:{label:'SHIFT',items:['SHIFT = 3','Move letters backward'],hint:'Decode the word.'},answer:'HELLO'},
 {title:'Constellation',type:'constellation',story:'The ceiling remembers a constellation only when the stars are named in order.',a:{label:'STAR MAP',items:['NORTH','EAST','SOUTH','WEST','CENTER']},b:{label:'STAR ORDER',items:['2','5','4','1','3'],hint:'Use the numeric order.'},answer:'EASTCENTERWESTNORTHSOUTH'},
 {title:'Twin Switch',type:'switch',story:'Two switches, two states. The correct state is hidden between both observations.',a:{label:'OBSERVATION A',items:['A ON','B OFF','C ON','D OFF']},b:{label:'OBSERVATION B',items:['A OFF','B OFF','C ON','D ON']},answer:'ABCD'},
 {title:'Memory of Stone',type:'memory',story:'The stone records a five-symbol chant. Each player sees a different half.',a:{label:'CHANT I',items:['◆','●','▲','■','●']},b:{label:'CHANT II',items:['◆','●','▲','■','●'],hint:'The sequence is identical. Confirm it exactly.'},answer:'◆●▲■●'},
 {title:'The Last Door',type:'final',story:'The Vault asks for the final phrase. Every previous chamber left one word behind.',a:{label:'WORDS',items:['THRESHOLD','SIGNAL','MIRROR','HELLO','STAR']},b:{label:'ORDER',items:['1','2','3','4','5'],hint:'Enter the words in their journey order.'},answer:'THRESHOLDSIGNALMIRRORHELLOSTAR'}
];
function roomCode(){return crypto.randomBytes(3).toString('hex').toUpperCase()}
function send(ws,msg){if(ws&&ws.readyState===1)ws.send(JSON.stringify(msg))}
function state(r){return {code:r.code,stage:r.stage,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,slot:p.slot,ready:p.ready})),solved:r.solved,started:r.started}}
function broadcast(r,msg){r.players.forEach(p=>send(p.ws,msg))}
function startRoom(r){if(r.players.size===2){r.started=true;broadcast(r,{type:'room',state:state(r),stage:stages[r.stage]})}}
const server=http.createServer((req,res)=>{let u=decodeURIComponent(req.url.split('?')[0]);if(u==='/')u='/index.html';let file=path.join(ROOT,u);if(!file.startsWith(ROOT))return res.writeHead(403).end();fs.readFile(file,(e,d)=>{if(e)return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(d)})});
function wsAccept(socket,head){const key=head['sec-websocket-key'];const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');return socket} function frame(text){const b=Buffer.from(text),l=b.length;let h;if(l<126){h=Buffer.from([129,l])}else if(l<65536){h=Buffer.alloc(4);h[0]=129;h[1]=126;h.writeUInt16BE(l,2)}else{h=Buffer.alloc(10);h[0]=129;h[1]=127;h.writeBigUInt64BE(BigInt(l),2)}return Buffer.concat([h,b])} function wsClient(socket){return {readyState:1,send:x=>{try{socket.write(frame(typeof x==='string'?x:JSON.stringify(x)))}catch{}},close:()=>socket.end()}} function parseFrames(socket,buf,handler){while(buf.length>=2){let b1=buf[0],b2=buf[1],masked=!!(b2&128),len=b2&127,off=2;if(len===126){if(buf.length<4)return buf;len=buf.readUInt16BE(2);off=4}else if(len===127){if(buf.length<10)return buf;len=Number(buf.readBigUInt64BE(2));off=10}let mask;if(masked){if(buf.length<off+4)return buf;mask=buf.subarray(off,off+4);off+=4}if(buf.length<off+len)return buf;let data=Buffer.from(buf.subarray(off,off+len));if(masked)for(let i=0;i<data.length;i++)data[i]^=mask[i%4];let op=b1&15;if(op===8){socket.end();return Buffer.alloc(0)}if(op===1)handler(data.toString());buf=buf.subarray(off+len)}return buf} server.on('upgrade',(req,socket,head)=>{if(req.headers.upgrade?.toLowerCase()!=='websocket'){socket.destroy();return}let raw=wsAccept(socket,req.headers);let ws=wsClient(socket),buffer=head||Buffer.alloc(0);let player=null;const handle=(raw)=>{let m;try{m=JSON.parse(raw)}catch{return} let player=null;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return} 
 if(m.type==='create'){let code;do{code=roomCode()}while(rooms.has(code));let r={code,stage:0,started:false,solved:false,players:new Map(),answers:[]};rooms.set(code,r);player={id:crypto.randomUUID(),name:String(m.name||'Player 1').slice(0,18),slot:1,ready:false,ws};r.players.set(player.id,player);send(ws,{type:'created',state:state(r)});return}
 if(m.type==='join'){let r=rooms.get(String(m.code||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Room not found.'});if(r.players.size>=2)return send(ws,{type:'error',message:'This vault already has two players.'});player={id:crypto.randomUUID(),name:String(m.name||'Player 2').slice(0,18),slot:2,ready:false,ws};r.players.set(player.id,player);broadcast(r,{type:'room',state:state(r),stage:stages[r.stage]});startRoom(r);return}
 if(!player)return;let r=[...rooms.values()].find(x=>x.players.has(player.id));if(!r)return;
 if(m.type==='ready'){player.ready=!!m.value;broadcast(r,{type:'room',state:state(r),stage:stages[r.stage]});startRoom(r)}
 if(m.type==='chat'){let text=String(m.text||'').slice(0,240);if(text)broadcast(r,{type:'chat',from:player.slot,name:player.name,text})}
 if(m.type==='solve'){if(!r.started||r.solved)return;let answer=String(m.answer||'').trim().toUpperCase().replace(/\s+/g,'');let expected=stages[r.stage].answer.toUpperCase().replace(/\s+/g,'');if(answer===expected){r.solved=true;broadcast(r,{type:'solved',stage:r.stage});setTimeout(()=>{if(!rooms.has(r.code))return;r.stage++;r.solved=false;if(r.stage>=stages.length){broadcast(r,{type:'complete',state:state(r)});rooms.delete(r.code)}else broadcast(r,{type:'next',state:state(r),stage:stages[r.stage]})},2200)}else send(ws,{type:'wrong'})}
 });}; socket.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);buffer=parseFrames(socket,buffer,handle)});socket.on('close',()=>{if(player){let r=[...rooms.values()].find(x=>x.players.has(player.id));if(r){r.players.delete(player.id);broadcast(r,{type:'left',message:'Your partner left the vault.',state:state(r)});if(r.players.size===0)rooms.delete(r.code)}}});});
server.listen(PORT,()=>console.log(`Echo Vault listening on ${PORT}`));
